### ISSUE TITLE
Der er elementer foran brættet

### ISSUE THREAD

**Issue by Zeydel** [diplomit-dtu/Matador_GUI#1]
Når man tilføjer 2 eller flere spillere, vil deres biler og pointtal være i vejen for spillets bræt
![image](https://user-images.githubusercontent.com/32457337/33151639-284eb06e-cfd9-11e7-88b6-e8a2054a231a.png)
#rip

**Comment by cbudtz** [comment]
Ja, det ser sgu lidt fjollet ud! Det må jeg se at få fikset

**Comment by ronnie-dalsgaard** [comment]
Nej, sådan er det også på det rigtige brætspil. Brikkerne står oven på feltet, så man ikke kan se feltet...!

Med venlig hilsen
Ronnie Dalsgaard

________________________________

**Comment by cbudtz** [comment]
:) Kig lidt nærmere, Ronnie - de biler der angiver spillerrens saldo og navn kolliderer med brædtet - Det er kommet af at jeg han lavet en opdatering, der tillader at man kun har 24 felter - Det får brædtet til at krympe, men jeg havde glemt at tænke på at det gav en kollision med spillernavnene...

**Comment by ronnie-dalsgaard** [comment]
I see...

Med venlig hilsen
Ronnie Dalsgaard

________________________________

**Comment by cbudtz** [comment]
Fixed!
