### ISSUE TITLE
fejl i setCar

### ISSUE THREAD

**Issue by ChristianSAndersen** [diplomit-dtu/Matador_GUI#2]
Når en bil er blevet vist med setCar for en spiller på et felt, vil hasCar altid returnere true, selv hvis bilen bliver fjernet for den pågældende spiller.

**Comment by cbudtz** [comment]
Besynderligt - men er det vigtigt? I virkeligheden burde metoden nok udgå...

**Comment by cbudtz** [comment]
Har fixet det - kommer med i version 3.1.3. Venter lidt med fejlrettelsen... Medmindre det er meget vigtigt for at komme videre? I burde kunne klare jer uden...
