### ISSUE TITLE
Spillernes placering

### ISSUE THREAD

**Issue by LordHjorth** [diplomit-dtu/Matador_GUI#3]
Hej Christian, 

Lækkert med den nye opdatering! Der er dog bare et lille problem. Når man opretter spillerne, kommer de til at stå oven i spillepladen. Er det noget vi selv kan fikse eller er det noget du måske lige vil kigge på? 

Har vedhæftet et screenshot, der viser problemet.

<img width="691" alt="skaermbillede 2017-11-23 kl 18 00 29" src="https://user-images.githubusercontent.com/32543877/33183453-37ac17aa-d078-11e7-99ee-cdcb1c3d6362.png">

Min fejl... Opdager lige at det er blevet rettet. Tak :-)

**Comment by cbudtz** [comment]
Fixed in version 3.12
