### ISSUE TITLE
Baggrundsfarven

### ISSUE THREAD

**Issue by Jaafar92** [diplomit-dtu/Matador_GUI#4]
Hej
Dette er ikke et issue, men bare et ønske. Er det muligt at få en "setter" til den grønne baggrundsfarve, så man selv kan bestemme hvad den skal være? 

Noget i stil med:

`GUI gui = new GUI();`
`gui.setBackgroundColor(new Color(0,150,136);`

**Comment by cbudtz** [comment]
Implemented with 3.1.3
